### ISSUE TITLE
Typo in  truth_values in function to_bool in generic_transformations.py  in AMI

### ISSUE THREAD

**Issue by GoogleCodeExporter** [IVRTech/pystrix#6]
```
There is a typo  ami/generic_transformations.py

In line 33, where it says:
        if truth_values:
should be:
        if truth_value:

truth_values is not defined, and changing that line works for me. Without 
changing that line, the action  SipShowPeer caused the following exception:

Traceback (most recent call last):
  File "/home/awainer/Documents/Aptana Studio 3 Workspace/voicesms3/voicesms/peermonitor.py", line 121, in <module>
    print ami_core._check_peer_status('obdpeer1')
  File "/home/awainer/Documents/Aptana Studio 3 Workspace/voicesms3/voicesms/peermonitor.py", line 98, in _check_peer_status
    return self._manager.send_action(action)
  File "/opt/python-voicesms/local/lib/python2.7/site-packages/pystrix/ami/ami.py", line 517, in send_action
    processed_response = request.process_response(response)
  File "/opt/python-voicesms/local/lib/python2.7/site-packages/pystrix/ami/core.py", line 1202, in process_response
    ), truth_value='Y')
  File "/opt/python-voicesms/local/lib/python2.7/site-packages/pystrix/ami/generic_transforms.py", line 33, in to_bool
    if truth_values:            
NameError: global name 'truth_values' is not defined.

The attached file can be used to reproduce the problem, provided you set the 
credentials and declare peers named obdpeer1 and obdpeer2.

```

Original issue reported on code.google.com by `awai...@gmail.com` on 22 Aug 2013 at 3:54

Attachments:
- [peermonitor.py](https://storage.googleapis.com/google-code-attachments/pystrix/issue-6/comment-0/peermonitor.py)

**Comment by karthicraghupathi** [comment]
This fix made it into the code before the project was migrated to GitHub.
